//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dropshipping_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Transaction
    {
        public int transaction_id { get; set; }
        public string entity_type { get; set; }
        public Nullable<int> entity_id { get; set; }
        public string transaction_type { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public string note { get; set; }
    }
}
