//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dropshipping_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessDBEntities2 : DbContext
    {
        public BusinessDBEntities2()
            : base("name=BusinessDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_Transaction> Account_Transaction { get; set; }
        public virtual DbSet<Client_Order_Item> Client_Order_Item { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment_Methods> Payment_Methods { get; set; }
        public virtual DbSet<Product_Price_History> Product_Price_History { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Supplier_Purchase_Item> Supplier_Purchase_Item { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
