//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dropshipping_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Client_Order_Item = new HashSet<Client_Order_Item>();
        }
    
        public int order_index { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> pay_method_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Order_Item> Client_Order_Item { get; set; }
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Payment_Methods Payment_Methods { get; set; }
    }
}
