//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dropshipping_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Price_History
    {
        public int price_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
