//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dropshipping_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.Supplier_Purchase_Item = new HashSet<Supplier_Purchase_Item>();
        }
    
        public int purchase_index { get; set; }
        public Nullable<int> purchase_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> pay_method_id { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Payment_Methods Payment_Methods { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Purchase_Item> Supplier_Purchase_Item { get; set; }
    }
}
